### ISSUE TITLE
[FEATURE] Add Performance Comparison to Other Thread Pool Implementations

### ISSUE THREAD

**Issue by DeveloperPaul123** [DeveloperPaul123/thread-pool#25]
Add performance comparisons via benchmarks to other thread pool implementations:

## Implementations to compare to

* [ ] https://github.com/bshoshany/thread-pool
* [ ] https://github.com/dkormalev/asynqro
* ~~[`QThreadPool`](https://doc.qt.io/qt-5/qthreadpool.html)~~
* [ ] [`boost::asio::thread_pool`](https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/reference/thread_pool.html)
* [ ] [`riften::ThiefPool`](https://github.com/ConorWilliams/Threadpool)

**Comment by VioletGiraffe** [comment]
Would be interesting to see a comparison to my implementation, can I get on the list? :) Don't take it for a shameless plug - mine is extremely similar to yours conceptually, but there are some implementation differences, for example I use `condition_variable` instead of a semaphore. Would be very curious to see which impl is better.

https://github.com/VioletGiraffe/cpputils/blob/master/threading/cworkerthread.h

**Comment by DeveloperPaul123** [comment]
Sure thing I can try and include your implementation as well or maybe you can file a PR once I have the basic setup going for comparative benchmarks (right now I only compare to `std::async`).

**Comment by VioletGiraffe** [comment]
Sure, good idea, I would of course do the job of adding my implementation to the bench suite once you have it.

**Comment by DeveloperPaul123** [comment]
@VioletGiraffe I've finished up the benchmark setup. Feel free to add in your library as a PR

**Comment by VioletGiraffe** [comment]
Hi! Can't build the benchmark on my Windows system / MSVC, do you happen to know how to fix it?

```
CPM: ConorWilliams_ThreadPool: Adding package ConcurrentDeque@1.1.0 (v1.1.0)
CMake Error at E:/THREAD-POOL/BUILD/_deps/concurrentdeque-src/CMakeLists.txt:30 (add_library):
  add_library INTERFACE library requires no source arguments.


CMake Error at E:/THREAD-POOL/BUILD/_deps/concurrentdeque-src/CMakeLists.txt:32 (target_compile_features):
  Cannot specify compile features for target "RiftenDeque" which is not built
  by this project.


CMake Error at E:/THREAD-POOL/BUILD/_deps/concurrentdeque-src/CMakeLists.txt:35 (target_compile_options):
  Cannot specify compile options for target "RiftenDeque" which is not built
  by this project.
```

**Comment by DeveloperPaul123** [comment]
@VioletGiraffe Yeah sometimes things are Cryptic. I wonder what the minimum CMake version is now for this project. I'll have to update it. Thanks for reporting the issue
