### ISSUE TITLE
Thread pool hangs indefinitely if job scheduled on running thread and all other threads have finished execution

### ISSUE THREAD

**Issue by jtd-formlabs** [DeveloperPaul123/thread-pool#40]
Please see this minimal example: 

```C++
#include <thread_pool/thread_pool.h>

#include <iostream>
#include <thread>

int main(int argc, const char *const *const argv) {
    dp::thread_pool thread_pool{ 2 };

    thread_pool.enqueue_detach([]() {
        int test;
        std::cin >> test;
        std::cout << "1\n";
    });
    thread_pool.enqueue_detach([]() {
        std::this_thread::sleep_for(std::chrono::seconds{ 1 });
        std::cout << "2\n";
    });
    std::this_thread::sleep_for(std::chrono::seconds{ 3 });
    thread_pool.enqueue_detach([]() {
        std::this_thread::sleep_for(std::chrono::seconds{ 1 });
        std::cout << "3\n";
    });

    return 0;
}
```

Thread 2 will never steal the job from thread 1, this will wait until user inputs something into the terminal.

Expected behavior is that thread 2 would run job 3 while thread 1 is still waiting.

**Comment by jtd-formlabs** [comment]
I believe one way to mitigate this is to change `void enqueue_task(Function &&f)` to have some priority scheduling instead of round robin. Threads that don't complete a task and go back to waiting put themselves at the top of the queue to receive new work, and long running threads fall to the bottom and have less things assigned.

**Comment by DeveloperPaul123** [comment]
Thank you for reporting this and for the PR!
