### ISSUE TITLE
Missing functions to get the return of some tasks

### ISSUE THREAD

**Issue by zh820952173** [DeveloperPaul123/thread-pool#65]
wait_for_tasks is wait for all tasks to complete

**Comment by DeveloperPaul123** [comment]
Could you elaborate on what you would expect function wise?

**Comment by zh820952173** [comment]
Lack of waiting for the specific task group  to return。for example， results = pool.wailtTasks(futures)

**Comment by DeveloperPaul123** [comment]
Oh I see.

Hmm, I'm not sure that this type of functionality belongs in the thread pool, but maybe the library can provide some convenience function for working with futures.

**Comment by zh820952173** [comment]
I think we need to have this feature。It would be even better if the library had this feature

**Comment by zh820952173** [comment]
wait_for_tasks is wait for all tasks. i hope wait_for_tasks(some tasks)

**Comment by DeveloperPaul123** [comment]
While I appreciate that this may be useful, this feature is beyond the scope of this library. I feel like it belongs in a concurrency library that works more generally with awaitable types or `std::futures`.
